### ISSUE TITLE
Documentation and views needed

### ISSUE THREAD

**Issue by emahuni** [rinvex/fort#10]
I'm still very new to Laravel and still learning some of the techniques. But I like your package a lot and am willing to contribute, but I've been scratching my head unnecessarily on how to implement this whole package and that alone can turn devs away.

 What I am missing is how to create abilities and roles, and then assign users to the created roles. It'll be great if views were included in the package to handle this and documentation to further show how to use the abilities and roles in the code.

Routes like:

`\auth\abilities` for CRUD of abilities
`\auth\roles` for CRUD of roles in conjunction with abilities
`\auth\user_roles` for assigning roles to users

There should also be a database seeding of an admin and a normal user role with a few exemplar roles and abilities packaged as publishables with fort.

**Comment by Omranic** [comment]
Hello @emahuni 
I totally agree with you, we've took your notes & worked hard to implement a dashboard for controlling abilities, roles, and users from the web UI for admins, so that's cool now. In regard to the docs we'll work hard on it in the upcoming few days in preparation for the official tagged release. Stay tuned, and thanks for your interest in our packages 😄
