### ISSUE TITLE
VERSION tagging needed

### ISSUE THREAD

**Issue by emahuni** [rinvex/fort#25]
One of the most terrifying thing to do to this package is update it.

I noticed that the last update i did, though it fixed several bugs, had breaking changes that didn't deserve to be in the same major version number as the one i had before the update, as stipulated by samver. It seems like updating this package just gives the current master changes.

Unless I am missing something, please tag this package to make it easy to update without fearing any breaking changes in the update.

**Comment by Omranic** [comment]
Thanks @emahuni for your feedback, you're completely right.
This package need to be tagged, and we've been leaving it without any official tags since it was still under heavy development and not yet ready for production, that's why we've added a **[WIP]** suffix to the package name (work in progress), where things are expected to break at anytime, without prior notice.

That said, we've been working lately intensively on this package forcing it towards stability, and we're very close to the minimal stable product that we'll tag then and announce it's official release. Expected to be this week -hopefully-

Thanks again, and stay tuned 😄
