### ISSUE TITLE
Laravel 5.3 on Valet

### ISSUE THREAD

**Issue by dinogit** [rinvex/fort#3]
Try to install it with `composer require rinvex/fort`. Got this error message: 

```
[InvalidArgumentException]

Could not find package rinvex/fort at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
```

When I try with : `composer require rinvex/fort ~1.0@dev`, I get:

```
Problem 1
    - Installation request for rinvex/fort ~1.0@dev -> satisfiable by rinvex/fort[1.0.x-dev].
    - rinvex/fort 1.0.x-dev requires rinvex/support dev-develop -> satisfiable by rinvex/support[dev-develop] but these conflict with your requirements or minimum-stability.
```

On Homestead, where I have a test project with Laravel 5.2, installation passes with no problem.

PHP version 7.0 on both.

**Comment by Omranic** [comment]
Greetings @dinogit 

Until this package is being tagged, you can add `"minimum-stability": "dev"` in your project's `composer.json` & it will install normally. Make sure to get latest version since we've pushed new important commits in the past few minutes.

Feel free to re-open this issue or another if you've anything else 👍
