### ISSUE TITLE
Problem with composer require

### ISSUE THREAD

**Issue by mits87** [rinvex/fort#34]
Hi,

I have an error when I try install rinvex/fort plugin to my project.
composer require rinvex/fort

>  [InvalidArgumentException]
>   Could not find package * at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

When I add manually this plugin to composer.json 
I got:

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for rinvex/fort dev-master -> satisfiable by rinvex/fort[dev-master].
>     - rinvex/fort dev-master requires rinvex/support dev-develop -> satisfiable by rinvex/support[dev-develop] but these conflict with your requirements or minimum-stability.

How can I properly install this plugin?
I'm using laravel 5.3

Best Regards
Peter

**Comment by emahuni** [comment]
You need to set minimum stability to 'dev' because fort is still work in progress and no stable release just yet. But I think most of the instability issues were fixed and it's just documentation and further minor debugging that's underway according to Omrac.  He said that he might do a stable release some time this week or next week. I'm not sure if it's going to pass through the other stages from dev, alpha, beta, RC, and  then stable... But the package is now good.

In the mean time add the following to your composer.json:

```json

{
    "require": {
        "rinvex/fort": "^1.0.*@dev"
    }
}

```

That will make it use the dev version.

If for some reason that doesn't work then as this:


```json

{
    "require": {
        "rinvex/fort": "^1.0.*@dev"
    },

   "minimum-stability":"dev"
}

```

Note that the above minimum-stability setting affects composer to filter packages by stability level globally in your project. According to that setting it may use dev versions of whatever package it is installing or updating.

**Comment by mits87** [comment]
hmm, when I add "rinvex/fort": "^1.0.*@dev" and set  "minimum-stability":"dev" then I got: 

>   [UnexpectedValueException]
>   Could not parse version constraint ^1.0.*: Invalid version string "^1.0.*"

**Comment by emahuni** [comment]
Ummmm remove ".*", I'll check later when on my project machine, but try that.

**Comment by mits87** [comment]
yes working now. But "minimum-stability":"dev" isn't good idea. 
Could you change stability of your plugin?

**Comment by Omranic** [comment]
@mits87 Yes, will do so soon once it's stable enough for a tagged release. I assure you that this package is our priority now, so we're giving it all our focus to push it forward and tag is ASAP 😃 

@emahuni Yes, we're probably will be going with a full release cycle, alpha, beta, and rc since this isn't a simple package and much feedback expected even after tagging it. Upcoming update to be released today with backward incompatibility and re-written phone verification feature, moving Authy token sending to a separate package utilizing Laravel notification channels. Sorry for the BC issues to happen 😅
